AWSTemplateFormatVersion : '2010-09-09'


Parameters:
  BucketName: 
    Type: String

Description: my template 123123
Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref BucketName
            
            
Outputs:
  OutputValue: 
    Value: !Ref MyBucket